### ISSUE TITLE
Simple way to change app logo

### ISSUE THREAD

**Issue by ChrisDryden** [gdg-toronto/Flutter-Study-Jam-Season-2#2]
I discovered a simple way to create your app icons for IOS and Android from a simple .png. First add the icon png to your project, I placed mine in "assets/icon.png"

Add the following dependency to your project in pubspec.yml
```flutter_launcher_icons: 0.7.3```

Then add the following code under the dependencies section:
```
flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
```
Then once the following command is run, you are all done:
```flutter_launcher_icons:main```
